namespace: telegram-bots

deployment:
  name: nhbot
  image: ghcr.io/preparingforexams/nhbot:__TAG__
  imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 1
  replicas: 1
  updateStrategy: Recreate
  labels:
    app: nhbot
  requests:
    cpu: 50m
    memory: 50Mi

secret:
  name: nhbot-telegram-token
  password: __TELEGRAM_TOKEN__
